#!/bin/bash

#SBATCH --partition=stdmem
#SBATCH --mail-type=ALL
#SBATCH -o %j.err

date
source /usr/share/Modules/init/bash
source /usr/local/Dist/amber/amber16/amber.sh
export PYTHONPATH=/usr/local/Dist/amber/amber16/lib/python2.7/site-packages:${PYTHONPATH}
module unload amber
module unload mvapich2-2.2
module load amber/16
#$AMBER_TRAJ_V
module list

MPI="mpiexec"
EXE="MMPBSA.py.MPI"
#INTERFACE="-iface ib0"
echo $SLURM_JOB_NODELIST
NODES=`scontrol show hostnames $SLURM_JOB_NODELIST | wc -l`
NSLOTS=$((NODES*SLURM_NTASKS_PER_NODE))

echo $NSLOTS
cd $SLURM_SUBMIT_DIR

$MPI -np $NSLOTS $EXE -O -i $T_DIR/scripts/mmgbsa.in -cp $T_DIR/data/complex_GB.prmtop -rp $T_DIR/data/receptor_GB.prmtop -lp $T_DIR/data/ligand_GB.prmtop -y $T_DIR/master.mdcrd -o FINAL_RESULTS_MMPBSA.dat -do FINAL_DECOMP_MMPBSA.dat



date



